### ISSUE TITLE
Add markers to the map for each collection center

### ISSUE THREAD

**Issue by ryanhamley** [Skycatch/acopio-ui#10]
We need to display a marker on the map for each collection center. The markers should also be in [clusters](https://www.mapbox.com/mapbox-gl-js/example/cluster/) since there may be quite a few centers in a relatively small area. They will need to be clickable (especially on mobile); clicking a marker should bring up a card with the center's information on it, but building the card will be a separate task.

**Comment by ryanhamley** [comment]
I believe @marioacc is working on this and has a pull request to add collection centers to the map.

**Comment by chubas** [comment]
Fixed in #15
