### ISSUE TITLE
CORS is preventing API access from the client

### ISSUE THREAD

**Issue by ryanhamley** [Skycatch/acopio-ui#11]
This might have to be one of the Skycatch team members @chubas @javierbyte or myself

**Comment by ryanhamley** [comment]
I haven't reproduced this. The API appears to be working fine for me.

**Comment by sauramirez** [comment]
I think @rbdr fixed this in the morning

**Comment by ryanhamley** [comment]
Ah, sweet thanks Essau. Closing this then.
