### ISSUE TITLE
Filter centers that appear on map by products

### ISSUE THREAD

**Issue by ryanhamley** [Skycatch/acopio-ui#12]
We should be able to search and filter the centers that appear on the map based on products that they need. This will help facilitate the movement of goods from centers with extra of an item to centers that need the item. It might be good to filter based on what the centers have as well to allow people who need certain items to find the closest center with that item.

**Comment by pedrogk** [comment]
The API is ready to support this. For example, https://hapi.balterbyte.com/api/productos?filter=%7B%22where%22%3A%20%7B%22nombre%22%3A%20%22agua%22%7D%7D provides the list of centers that need water (agua).
