### ISSUE TITLE
Implement Mapbox GL

### ISSUE THREAD

**Issue by ryanhamley** [Skycatch/acopio-ui#2]
Mapbox GL will be used to render a map of collection centers. Expect the API to return lat/lng coordinates for each center.

**Comment by ryanhamley** [comment]
Step 1: Show map with all collection centers on it (center on Mexico City)
Step 2: Allow user to geolocate map on themselves (by clicking a button to do it automatically or by entering an address into a search field)
Step 3: Find closest center to geolocated location

**Comment by marioacc** [comment]
I am taking a look to the Mapbox GL docs for the implementation 😄

**Comment by marioacc** [comment]
@ryanhamley, do the team has a key to start using Mapbox GL?

**Comment by ryanhamley** [comment]
Hey @marioacc I began the process of implementing this and merged a PR with a very basic map set up as a React component. I'm using the [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md) plugin for it. Let me know if you have any thoughts or questions.

**Comment by marioacc** [comment]
Perfect @ryanhamley I will take a look.

**Comment by ryanhamley** [comment]
We should probably close this issue and create more specific ones for adding features to the map. Thoughts @chubas ?

**Comment by marioacc** [comment]
@ryanhamley I will start testing a way to add collection centers to the map.

**Comment by sbaidon** [comment]
I agree we should start creating more specific issues so that more people can come and help
