### ISSUE TITLE
Manage contact info for a center

### ISSUE THREAD

**Issue by pedrogk** [Skycatch/acopio-ui#27]
Once you create a center, you should be able to add contacts.

The endpoint to work with is /acopios/{acopio-id}/contactos   (it should already support POST/PUT/)

A contact object would end up looking like:

`  {
    "nombre": "Juan Perez",
    "email": "juan@gmail.com",
    "twitter": "@blah",
    "facebook": "fb.com/blah",
    "telefono": "55 2561 9561",
    "id": "59c4c11400220a53359e0983",
    "acopioId": "59c4c11400220a53359e0982"
  }
`

id: being the id of the contact (auto-generated) and acopioId being the id of the center in question.

Some centers only provide an email, others a facebook page, others the name of a person and a phone. Therefore, all fields are optional but we need at least one of the fields to be filled.

**Comment by oscaroceguera** [comment]
Tengo estas dudas:
* Se tendrá una lista de de contactos para poder editar y eliminar?
* Se ocupa un filtrado por acopioId para la lista de centros agregados?

**Comment by jeduan** [comment]
Closed in #46
