### ISSUE TITLE
Manage needs for a center

### ISSUE THREAD

**Issue by pedrogk** [Skycatch/acopio-ui#30]
Add/edit the needs (productos) for a center.

**Comment by jeduan** [comment]
The deliverable for this is:

On `/components/admin/*`
Create a `ProductList` component 

routes
this component will be added to `CenterAdmin`

### ProductList

Should list all the current products needed for a Center
Every product must have a link to modify quantity, or delete
Must be able to set a product as fulfilled
Must be able to add a needed product

### API endpoints

[`GET /acopios/:id/productos`](https://hapi.balterbyte.com/explorer/#!/acopio/acopio_prototype_get_productos)
[`POST /acopios/:id/productos`](https://hapi.balterbyte.com/explorer/#!/acopio/acopio_prototype_create_productos)

**Comment by Ikana** [comment]
I'm on it @jeduan

**Comment by jeduan** [comment]
Fixed on #61
