### ISSUE TITLE
Get the last updated date for Acopio

### ISSUE THREAD

**Issue by jeduan** [Skycatch/acopio-ui#57]
Each `acopio` has `products` and each `product` has a `fechaDeActualizacion` string. Surface the  latest `fechaDeActualización` on `AcopioCard`

If needed, use [`date-fns`](https://date-fns.org/) to sort the dates.

**Comment by diegovdc** [comment]
acá una propuesta: #62

**Comment by jeduan** [comment]
Fixed on #62
