### ISSUE TITLE
Cargar lista de centros de acopio independientemente de acceso a geolocalización

### ISSUE THREAD

**Issue by jeduan** [Skycatch/acopio-ui#72]
Al iniciar la app, el usuario debería de ver una lista limitada de centros (20 items). En esta pantalla el usuario puede explorar y permitir el acceso a geolocalización.

Cuando se permite la geolocalización, se debe de cambiar la información por los centros más cercanos.

**Comment by ldelriof** [comment]
https://github.com/Skycatch/acopio-ui/pull/85
