### ISSUE TITLE
Buscar centros de acopio por producto

### ISSUE THREAD

**Issue by jeduan** [Skycatch/acopio-ui#75]
Necesitamos una vista para buscar centros de acopio por producto.

APIs a usar:

 - `api.getProductosByPartialName`

Componentes

[AutoComplete](http://www.material-ui.com/#/components/auto-complete)

**Comment by huhgawz** [comment]
@jeduan me podrias asignar este issue?

**Comment by huhgawz** [comment]
Working on this

**Comment by huhgawz** [comment]
Working on this issue

**Comment by jeduan** [comment]
Asignado a @huhgawz

**Comment by huhgawz** [comment]
Adding mockup for reference:

![center-by-product](https://user-images.githubusercontent.com/369338/30779359-e244beb4-a0b3-11e7-899a-ae02ba785625.png)

**Comment by huhgawz** [comment]
Implemented in #93 and #100
