### ISSUE TITLE
Extender mensaje "No encontramos centros de acopio"

### ISSUE THREAD

**Issue by pedrogk** [Skycatch/acopio-ui#89]
La primer página de la app muestra una lista de centros de acopio cerca de donde estás. Pero si no encuentra ninguno cercano te da el mensaje "No encontramos centros de acopio". Si yo como usuario novato entro y lo primero que me sale es eso, pienso que es un error porque parece que no hubiera centros de acopio en ningún lado. Así que hay que modificar el texto para que diga "No encontramos centros de acopio cerca de ti".

**Comment by diegovdc** [comment]
ya está cerrado verdad?

**Comment by jeduan** [comment]
Si, aunque necesitamos mejores empty states
