### ISSUE TITLE
Pasar valor de texto en busqueda de productos a lower case.

### ISSUE THREAD

**Issue by pedrogk** [Skycatch/acopio-ui#95]
Al buscar por producto, hay teléfonos que por default te ponen mayúscula la primer letra. Entonces si tecleas 'agua' sale 'Agua' y la búsqueda no regresa resultados (porque todo está lower case en la api).

**Comment by diegovdc** [comment]
@pedrogk,  @huhgawz  está en esto, lo puedes asignar porfa?

**Comment by jeduan** [comment]
Implementado en #93
